
const bartstations = [

    {name: "12th",
    full_name : "12th St. Oakland City Center"},
    {name: "16th",
    full_name: "16th St. Mission (SF)"},
    {name: "19th",
    full_name: "19th St. Oakland"},
    {name: "24th",
    full_name: "24th St. Mission (SF)"},
    {name: "ashb",
    full_name: "Ashby (Berkeley)"},
    {name: "antc",
    full_name: "Antioch"},
    {name: "balb",
    full_name: "Balboa Park (SF)"},
    {name: "bayf",
    full_name: "Bay Fair (San Leandro)"},
    {name: "bery",
    full_name: "Berryessa / North San Jose"},
    {name: "cast",
    full_name: "Castro Valley"},
    {name: "civc",
    full_name: "Civic Center (SF)"},
    {name: "cols",
    full_name: "Coliseum"},
    {name: "colm",
    full_name: "Colma"},
    {name: "conc",
    full_name: "Concord"},
    {name: "daly",
    full_name: "Daly City"},
    {name: "dbrk",
    full_name: "Downtown Berkeley"},
    {name: "dubl",
    full_name: "Dublin/Pleasanton"},
    {name: "deln",
    full_name: "El Cerrito del Norte"},
    {name: "plza",
    full_name: "El Cerrito Plaza"},
    {name: "embr",
    full_name: "Embarcadero (SF)"},
    {name: "frmt",
    full_name: "Fremont"},
    {name: "ftvl",
    full_name: "Fruitvale (Oakland)"},
    {name: "glen",
    full_name: "Glen Park (SF)"},
    {name: "hayw",
    full_name: "Hayward"},
    {name: "lafy",
    full_name: "Lafayette"},
    {name: "lake",
    full_name: "Lake Merritt (Oakland)"},
    {name: "mcar",
    full_name: "MacArthur (Oakland)"},
    {name: "mlbr",
    full_name: "Millbrae"},
    {name: "mlpt",
    full_name: "Milpitas"},
    {name: "mont",
    full_name: "Montgomery St. (SF)"},
    {name: "nbrk",
    full_name: "North Berkeley"},
    {name: "ncon",
    full_name: "North Concord/Martinez"},
    {name: "oakl",
    full_name: "Oakland Int'l Airport"},
    {name: "orin",
    full_name: "Orinda"},
    {name: "pitt",
    full_name: "Pittsburg/Bay Point"},
    {name: "pctr",
    full_name: "Pittsburg Center"},
    {name: "phil",
    full_name: "Pleasant Hill"},
    {name: "powl",
    full_name: "Powell St. (SF)"},
    {name: "rich",
    full_name: "Richmond"},
    {name: "rock",
    full_name: "Rockridge (Oakland)"},
    {name: "sbrn",
    full_name: "San Bruno"},
    {name: "sfia",
    full_name: "San Francisco Int'l Airport"},
    {name: "sanl",
    full_name: "San Leandro"},
    {name: "shay",
    full_name: "South Hayward"},
    {name: "ssan",
    full_name: "South San Francisco"},
    {name: "ucty",
    full_name: "Union City"},
    {name: "warm",
    full_name: "Warm Springs/South Fremont"},
    {name: "wcrk",
    full_name: "Walnut Creek"},
    {name: "wdub",
    full_name: "West Dublin"},
    {name: "woak",
    full_name: "West Oakland"}

    // "19th": "19th St. Oakland",
    // "24th": "24th St. Mission (SF)",
    // "ashb": "Ashby (Berkeley)",
    // "antc": "Antioch",
    // "balb": "Balboa Park (SF)",
    // "bayf": "Bay Fair (San Leandro)",
    // "bery": "Berryessa / North San Jose",
    // "cast": "Castro Valley",
    // "civc": "Civic Center (SF)",
    // "cols": "Coliseum",
    // "colm": "Colma",
    // "conc": "Concord",
    // "daly": "Daly City",
    // "dbrk": "Downtown Berkeley",
    // "dubl": "Dublin/Pleasanton",
    // "deln": "El Cerrito del Norte",
    // "plza": "El Cerrito Plaza",
    // "embr": "Embarcadero (SF)",
    // "frmt": "Fremont",
    // "ftvl": "Fruitvale (Oakland)",
    // "glen": "Glen Park (SF)",
    // "hayw": "Hayward",
    // "lafy": "Lafayette",
    // "lake": "Lake Merritt (Oakland)",
    // "mcar": "MacArthur (Oakland)",
    // "mlbr": "Millbrae",
    // "mlpt": "Milpitas",
    // "mont": "Montgomery St. (SF)",
    // "nbrk": "North Berkeley",
    // "ncon": "North Concord/Martinez",
    // "oakl": "Oakland Int'l Airport",
    // "orin": "Orinda",
    // "pitt": "Pittsburg/Bay Point",
    // "pctr": "Pittsburg Center",
    // "phil": "Pleasant Hill",
    // "powl": "Powell St. (SF)",
    // "rich": "Richmond",
    // "rock": "Rockridge (Oakland)",
    // "sbrn": "San Bruno",
    // "sfia": "San Francisco Int'l Airport",
    // "sanl": "San Leandro",
    // "shay": "South Hayward",
    // "ssan": "South San Francisco",
    // "ucty": "Union City",
    // "warm": "Warm Springs/South Fremont",
    // "wcrk": "Walnut Creek",
    // "wdub": "West Dublin",
    // "woak": "West Oakland"}
]
export default bartstations;
